export const GET_SECRETS = 'GET_SECRETS';
export const GET_SECRETS_SUCCESS = 'GET_SECRETS_SUCCESS';
export const GET_SECRETS_ERROR = 'GET_SECRETS_ERROR';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
